import { useState } from 'react';
import Head from 'next/head';
import { format } from 'date-fns';
import { enGB } from 'date-fns/locale';
import DatePicker from '../components/DatePicker';
import RangePicker from '../components/RangePicker';

import 'react-nice-dates/build/style.css';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  const [date, setDate] = useState(new Date());

  const [startDate, setStartDate] = useState<Date | null>(null);
  const [endDate, setEndDate] = useState<Date | null>(null);

  return (
    <div>
      <Head>
        <title>Date picker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center py-10 gap-y-10">
        <p>
          {date ? format(date, 'ccc, dd MMM HH:mm', { locale: enGB }) : 'none'}
        </p>
        <DatePicker date={date} setDate={setDate} />

        <p>
          {startDate
            ? format(startDate, 'ccc, dd MMM HH:mm', { locale: enGB })
            : 'none'}
          {' - '}
          {endDate
            ? format(endDate, 'ccc, dd MMM HH:mm', { locale: enGB })
            : 'none'}
        </p>
        <RangePicker {...{ startDate, setStartDate, endDate, setEndDate }} />
      </main>
    </div>
  );
};

export default Home;
