import { useEffect, useState } from 'react';
import Head from 'next/head';
import { format } from 'date-fns';
import { enGB } from 'date-fns/locale';
import DatePicker from '../components/DatePicker';
import RangePicker from '../components/RangePicker';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  const [date, setDate] = useState(new Date());

  const [startDate, setStartDate] = useState<Date | null>(null);
  const [endDate, setEndDate] = useState<Date | null>(null);

  const [showChild, setShowChild] = useState(false);

  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }

  return (
    <div>
      <Head>
        <title>Date picker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center py-10 gap-y-10">
        <section className="flex flex-col items-center w-full">
          <h2 className="text-xl font-semibold m-2">Date Picker</h2>
          <p className="mb-5">
            {date
              ? format(date, 'ccc, dd MMM HH:mm', { locale: enGB })
              : 'none'}
          </p>
          <DatePicker date={date} setDate={setDate} />
        </section>
        <section className="flex flex-col items-center w-full">
          <h2 className="text-xl font-semibold m-2">Range Picker</h2>
          <p className="mb-5">
            {startDate
              ? format(startDate, 'ccc, dd MMM HH:mm', { locale: enGB })
              : 'none'}
            {' - '}
            {endDate
              ? format(endDate, 'ccc, dd MMM HH:mm', { locale: enGB })
              : 'none'}
          </p>
          <RangePicker {...{ startDate, setStartDate, endDate, setEndDate }} />
        </section>
      </main>
    </div>
  );
};

export default Home;
